# 컴퓨터들
services: 

  # 컴퓨터이름
  my-backend: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7010:7010

  # 컴퓨터이름
  my-database:
    image: mongo:5
    # ports:
    #   - 27017:27017 => 몽고DB 컴패스에서 접속안됨.
    #                    하지만, 네임리졸루션으로 express에서는 접속됨.
