# 컴퓨터들
services: 

  # 컴퓨터이름
  my-backend: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7010:7010

  # 컴퓨터이름
  my-database:
    build:
      context: .
      dockerfile: Dockerfile.mongo  
    ports:
      - 27017:27017
